Added btns and catching errors
atagiev/ai-image-editor pull request #39
Opened 2022-01-07 12:19 UTC by AnastasiaShreder

Сделаны F_DEFAULT_1, F_OPEN_1, F_OPEN_2

2022-01-07 13:01 UTC, atagiev commented
Лишний файл logs/log_file-2022-01-07-12-50-04.log

2022-01-07 13:06 UTC, atagiev requested changes

2022-01-07 13:06 UTC, atagiev commented on web/vue-spa/src/App.vue
> +      axios.get(' http://localhost:5000/ping')
Мб лишний пробел перед запросом

2022-01-07 13:23 UTC, AnastasiaShreder commented on web/vue-spa/src/App.vue
> +      axios.get(' http://localhost:5000/ping')
Поправила в новом коммите

2022-01-07 13:24 UTC, AnastasiaShreder commented
> Лишний файл logs/log_file-2022-01-07-12-50-04.log

удалила

2022-01-07 15:47 UTC, atagiev requested changes

2022-01-07 15:47 UTC, atagiev commented on web/vue-spa/src/components/Footer.vue
> +          console.log('Загружена картинка и инструменты редактирвоания ', response)
очепятка

2022-01-07 15:49 UTC, atagiev commented
> > Лишний файл logs/log_file-2022-01-07-12-50-04.log
> 
> удалила

Не удалился

2022-01-07 16:47 UTC, AnastasiaShreder commented
> > > Лишний файл logs/log_file-2022-01-07-12-50-04.log
> > 
> > 
> > удалила
> 
> Не удалился

теперь удалился

2022-01-07 17:43 UTC, atagiev requested changes

2022-01-07 17:43 UTC, atagiev commented on web/vue-spa/src/components/Footer.vue
> +              if (response.data.w <= 1920 && response.data.h <= 1080) {
А мы не будем поддерживать фото 1080x1920?

2022-01-07 17:43 UTC, atagiev commented on web/vue-spa/src/components/Footer.vue
> +              if (response.data.w <= 1920 && response.data.h <= 1080) {
Мб стоит добавить "or response.data.w <= 1080 && response.data.h <= 1920"

2022-01-07 17:48 UTC, AnastasiaShreder commented on web/vue-spa/src/components/Footer.vue
> +              if (response.data.w <= 1920 && response.data.h <= 1080) {
да, не подумала что-то, в след коммите добавлю

2022-01-08 16:03 UTC, atagiev approved these changes

2022-01-08 17:10 UTC, merged